bl_temp=cv2.getTrackbarPos('bl', 'temp')
        # gl_temp=cv2.getTrackbarPos('gl', 'temp')
        # rl_temp=cv2.getTrackbarPos('rl', 'temp')
        # bh_temp=cv2.getTrackbarPos('bh', 'temp')
        # gh_temp=cv2.getTrackbarPos('gh', 'temp')
        # rh_temp=cv2.getTrackbarPos('rh', 'temp')